import React, { useState, useRef, useEffect } from 'react';
import { motion } from 'framer-motion';
import { ChevronLeftIcon, ChevronRightIcon } from '@heroicons/react/24/outline';

type Props = {}

export default function Projects({ }: Props) {
    const [currentProjectIndex, setCurrentProjectIndex] = useState(0);
    const scrollContainerRef = useRef<HTMLDivElement>(null);

    const goToPreviousProject = () => {
        if (scrollContainerRef.current) {
            const container = scrollContainerRef.current;
            const scrollAmount = container.clientWidth;
            container.scrollBy({
                left: -scrollAmount,
                behavior: 'smooth'
            });
        }
    };

    const goToNextProject = () => {
        if (scrollContainerRef.current) {
            const container = scrollContainerRef.current;
            const scrollAmount = container.clientWidth;
            container.scrollBy({
                left: scrollAmount,
                behavior: 'smooth'
            });
        }
    };

    // Update current project index based on scroll position
    useEffect(() => {
        const container = scrollContainerRef.current;
        if (!container) return;

        const handleScroll = () => {
            const scrollLeft = container.scrollLeft;
            const projectWidth = container.clientWidth;
            const newIndex = Math.round(scrollLeft / projectWidth);
            setCurrentProjectIndex(newIndex);
        };

        container.addEventListener('scroll', handleScroll);
        return () => container.removeEventListener('scroll', handleScroll);
    }, []);

    const projects = [
        {
            image: "/aigen.png",
            name: "AI Background Generator",
            summary: [
                "Developed a web app using Angular and Python to automatically remove background from an image and replace it with image generated by AI based on user provided text prompt"
            ]
        },
        {
            image: "/protrac.png",
            name: "ProTrac",
            summary: [
                "Developed a Project Management Software with focus on task management, scheduling, and record keeping for Slnko Energy using Angular, MongoDB, and Node.js and deployed it on AWS"
            ]
        },
        {
            image: "/dsm.png",
            name: "Daily Stock Metrics",
            summary: [
                "Developed a web application using Angular and Java responsible for showing the analysis of different stocks by caching the relevant stock data in Apache Ignite clusters, collected by scraping data from multiple websites"
            ]
        },
        {
            image: "/village.png",
            name: "Village Land Auction",
            summary: [
                "- Led a team of 3 to develop backend and multi-lingual, user-friendly UI of an Android app used to organize events, handle payments, and capture auction details, saving time and reducing the cost of conducting the auctions significantly",
                "- Designed and built a responsive website using React, Node.js, and MySql to help admin manage and visualize auction data"
            ]
        },
        {
            image: "/handwritting.jpg",
            name: "Automatic Personality Traits Detection using Handwriting",
            summary: [
                "- Created a deep learning CNN model using TensorFlow and Keras to detect the personality of a person with 76% accuracy using 800 handwriting samples of more than 200 individuals",
                "- Developed an Android application to scan handwriting samples and show predicted personality traits"
            ]
        },
        {
            image: "/cancer.png",
            name: "Cancer Prediction using XGBoost",
            summary: [
                "- Trained a machine learning model using Python with a real dataset of 1800 patients collected by Department of Biotechnology, TIET to predict lung cancer with 78% accuracy",
                "- Processed raw data using statistical methods to filter out unwanted data and used Python libraries to visualize and compare performance of different machine learning models. Also created a website to predict cancer using the trained model"
            ]
        }
    ];
    return (
        <motion.div
            initial={{
                opacity: 0
            }}
            whileInView={{
                opacity: 1
            }}
            transition={{
                duration: 1.5
            }}
            className='relative z-0 flex flex-col items-center h-screen max-w-full mx-auto overflow-hidden text-left md:flex-row justify-evenly'>
            <h3 className='absolute top-24 uppercase tracking-[15px] sm:tracking-[20px] text-gray-500 text-lg sm:text-2xl'>
                Projects
            </h3>

            {/* Previous Button */}
            <button
                onClick={goToPreviousProject}
                className='hidden sm:block absolute left-4 sm:left-8 z-30 bg-[#F7AB0A]/20 hover:bg-[#F7AB0A]/40 rounded-full p-2 sm:p-3 transition-all duration-300 hover:scale-110'
                aria-label="Previous project"
            >
                <ChevronLeftIcon className='h-6 w-6 sm:h-8 sm:w-8 text-[#F7AB0A]' />
            </button>

            <div ref={scrollContainerRef} className='relative w-full flex overflow-x-scroll overflow-y-hidden snap-x snap-mandatory z-20 scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]'>
                {projects.map((project, i) => (
                    <div key={i} className='flex flex-col items-center justify-center flex-shrink-0 w-screen h-screen p-8 sm:p-16 md:p-20 lg:p-44 snap-center snap-y-5'>
                        <motion.img
                            initial={{
                                y: -300,
                                opacity: 0
                            }}
                            transition={{
                                duration: 1.5
                            }}
                            whileInView={{
                                y: 0,
                                opacity: 1
                            }}
                            viewport={{
                                once: true
                            }}
                            className='w-auto h-32 sm:h-40 md:h-48 lg:h-72 object-scale-down mb-6 sm:mb-10'
                            src={project.image}
                        />

                        <div suppressHydrationWarning={true} className='max-w-6xl px-0 space-y-10 md:px-10'>
                            <h4 className='text-2xl sm:text-4xl font-semibold text-center underline decoration-[#F7AB0A]/50'>{project.name}</h4>
                            <div className='text-sm text-center sm:text-lg md:text-left'>
                                <ul className='space-y-3'>
                                    {project.summary.map((detail: string, i : any) => (
                                        <li key={i} className='text-justify'>{detail}</li>
                                    ))}
                                </ul>
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* Next Button */}
            <button
                onClick={goToNextProject}
                className='hidden sm:block absolute right-4 sm:right-8 z-30 bg-[#F7AB0A]/20 hover:bg-[#F7AB0A]/40 rounded-full p-2 sm:p-3 transition-all duration-300 hover:scale-110'
                aria-label="Next project"
            >
                <ChevronRightIcon className='h-6 w-6 sm:h-8 sm:w-8 text-[#F7AB0A]' />
            </button>

            {/* Project Indicators */}
            <div className='absolute bottom-8 sm:bottom-12 left-1/2 transform -translate-x-1/2 flex space-x-2 z-30'>
                {projects.map((_, index) => (
                    <button
                        key={index}
                        onClick={() => {
                            if (scrollContainerRef.current) {
                                const container = scrollContainerRef.current;
                                const scrollAmount = container.clientWidth * index;
                                container.scrollTo({
                                    left: scrollAmount,
                                    behavior: 'smooth'
                                });
                            }
                        }}
                        className={`w-2 h-2 sm:w-3 sm:h-3 rounded-full transition-all duration-300 ${
                            index === currentProjectIndex 
                                ? 'bg-[#F7AB0A] scale-125' 
                                : 'bg-gray-500 hover:bg-gray-400'
                        }`}
                        aria-label={`Go to project ${index + 1}`}
                    />
                ))}
            </div>

            <div className='w-full absolute top-[30%] bg-[#F7AB0A]/10 left-0 h-[500px] -skew-y-12'></div>
        </motion.div>
    )
}